apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bXlUZXN0VXNlcg==
  mongo-root-password: bXlTZWNyZXRQYXNzd29yZA==
#  my-custom-secret: YWRtaW4=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service&slaveOk=true
